FROM --platform=linux/amd64 node:24-slim AS build

WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@10 --activate

COPY . .

RUN pnpm install --frozen-lockfile

ENV NODE_ENV=production
ENV PORT=19176
ENV BASE_PATH=/

RUN pnpm --filter @workspace/magazzino-solidale run build


FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/artifacts/magazzino-solidale/dist/public /usr/share/nginx/html

EXPOSE 80
